version: '3.9'

services:
  database:
    container_name: db_bective
    image: postgres:12.8
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    container_name: backend_bective
    env_file:
      - .env
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - database
    restart: always
  frontend:
    container_name: frontend_bective
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    restart: always
volumes:
  db:
