version: '3.9'

services:
  database:
    container_name: db_bective
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - net
  adminer:
    image: dockette/adminer
    restart: always
    ports:
      - '8081:80'
  backend:
    container_name: backend_bective
    env_file:
      - .env
    build: ./backend
    ports:
      - '8080:3000'
    depends_on:
      - database
    restart: always
    volumes:
      - ./backend:/bective/back
    networks:
      - net
  frontend:
    container_name: frontend_bective
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    restart: always
    volumes:
      - ./frontend/src:/bective/front/src

volumes:
  db:
networks:
  net:
    driver: bridge
