version: '3.9'

services:
  database:
    container_name: bective_db
    image: postgres:12.8
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
  backend:
    container_name: bective_api
    env_file:
      - .env
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - database
    restart: always

volumes:
  db:
