name: Bective

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build frontend
        run: |
          cd frontend
          yarn install
          yarn build
  lint-front:
    needs: [build-front]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint frontend
        run: |
          cd frontend
          yarn install
          yarn lint
  build-back:
    needs: [lint-front]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - name: build backend
        run: |
          cd backend
          go build -v
